# Gulp will reference these paths when it copies files
PATH:
  # Path to source folder
  src: "."
  # Path to temp folder
  tmp: "./tmp"
  # Path to web folder
  web: "../../build"

FOLDERS:
  scss: "/scss"
  css: "/css"
  img: "/img"
  js: "/js"
  fonts: "/fonts"
  svg: "/svg"
